# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json
name: sample-web-app
scope: Namespaced
defaultNamespace: sample-web-app
shortDescription: A sample Node.js web application
longDescription: |
  ## Sample Web App
  This is a sample Node.js web application that can be deployed to Kubernetes.
  
  ### Features
  - Simple Node.js server
  - Containerized with Docker
  - Deployed with Helm
  
  ### Getting Started
  Once deployed, you can access the application via your browser at your configured hostname.
  The application displays a simple "Hello World" page with Node.js information.

iconUrl: https://cdn-icons-png.flaticon.com/512/919/919825.png

# Using the Helm chart approach
helm:
  chartName: eap-distr-simulator
  chartVersion: 0.1.0
  # Using GitHub raw content URL
  repositoryUrl: https://raw.githubusercontent.com/pkhsu/glasskube-gitops-test/main/apps/sample-web-app/chart/

valueDefinitions:
  replicaCount:
    metadata:
      description: "Number of replicas to run"
      label: "Replicas"
    type: number
    defaultValue: "1"
    targets:
      - chartName: eap-distr-simulator
        patch:
          op: replace
          path: /replicaCount
  ingressEnabled:
    metadata:
      description: "Enable ingress for external access"
      label: "Enable Ingress"
    type: boolean
    defaultValue: "false"
    targets:
      - chartName: eap-distr-simulator
        patch:
          op: replace
          path: /ingress/enabled
  ingressHost:
    metadata:
      description: "Hostname for the ingress"
      label: "Ingress Hostname"
    type: text
    defaultValue: "sample-web-app.example"
    targets:
      - chartName: eap-distr-simulator
        patch:
          op: replace
          path: /ingress/hosts/0/host
  resources:
    metadata:
      description: "Configure CPU/Memory resource limits"
      label: "Resource Limits"
    type: boolean
    defaultValue: "false"
    targets:
      - chartName: eap-distr-simulator
        valueTemplate: '{{if .}}{ "requests": { "cpu": "100m", "memory": "128Mi" }, "limits": { "cpu": "300m", "memory": "256Mi" } }{{else}}null{{end}}'
        patch:
          op: replace
          path: /resources

values:
  # Make sure base structure exists for valueDefinitions
  ingress:
    hosts:
      - host: ""
        paths: 
          - path: /
            pathType: Prefix
  resources: null

entrypoints:
  - name: web-ui
    serviceName: sample-web-app
    port: 80
    localPort: 3000
    scheme: http

references:
  - label: "Node.js Documentation"
    url: "https://nodejs.org/en/docs/"
  - label: "Repository"
    url: "https://github.com/pkhsu/glasskube-gitops-test/tree/main/apps/sample-web-app"
  - label: "Docker Hub"
    url: "https://hub.docker.com/_/node" 