apiVersion: v2
name: sample-web-app
description: A Helm chart for deploying the Sample Web Application
type: application
version: 0.1.1 # Chart version
appVersion: "1.0.1" # Application version (matches package.json)
