# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json
apiVersion: packages.glasskube.dev/v1
kind: PackageManifest
name: sample-web-app
scope: Namespaced
defaultNamespace: sample-web-app
shortDescription: A sample Node.js web application
longDescription: |
  ## Sample Web App
  This is a sample Node.js web application that can be deployed to Kubernetes.
  
  ### Features
  - Simple Node.js server
  - Containerized with Docker
  - Deployed with Helm
  
  ### Getting Started
  Once deployed, you can access the application via your browser at your configured hostname.
  The application displays a simple page with a REST API for simulating distribution.

iconUrl: https://cdn-icons-png.flaticon.com/512/919/919825.png

# ---
# This section demonstrates how Glasskube's package configuration system enables dynamic value injection into Helm charts.
#
# 1. The 'values' block under the Helm chart provides default values for the chart deployment. Here, it sets 'env.CUSTOM_MESSAGE'.
# 2. The 'valueDefinitions.customMessage' entry (not shown here, but implied) allows users to override or supply this value at install time.
# 3. The 'targets' block under the value definition specifies how the user-supplied or default value should patch the Helm chart's values using a JSON patch operation.
#    - In this example, the patch operation targets '/env/CUSTOM_MESSAGE' in the Helm values, enabling dynamic configuration.
#
# For more details, see:
# https://glasskube.dev/products/package-manager/docs/design/package-config/#how-does-a-value-affect-the-deployed-package-resources
# ---

# 使用標準的Helm chart方式
helm:
  chartName: sample-web-app
  chartVersion: "0.1.1" # Updated chart version
  # 指向GitHub raw內容作為Helm repository
  repositoryUrl: https://raw.githubusercontent.com/pkhsu/glasskube-package-test/main/helm-repo/
  values:
    env:
      CUSTOM_MESSAGE: "Messages from package.yaml helm block."
  # values:
  #   env: {}
      
valueDefinitions:
  customMessage:
    metadata:
      description: "Enter the custom message to be displayed by the web app."
      longDescription: "This message will be passed as an environment variable (CUSTOM_MESSAGE) to the application and shown on its main page."
    type: text
    default: "Message from: Glasskube UI default (v1.0.1+1)"
    constraints:
      required: false
      maxLength: 100
    targets:
      - chartName: sample-web-app
        patch:
          op: add
          path: /env/CUSTOM_MESSAGE # This corresponds to the path in values.yaml

entrypoints:
  - name: web-ui
    serviceName: sample-web-app
    port: 80
    localPort: 3100
    scheme: http
    context: /
  - name: api
    serviceName: sample-web-app
    port: 80
    localPort: 3101
    scheme: http
    context: /distribute

references:
  - label: "Node.js Documentation"
    url: "https://nodejs.org/en/docs/"
  - label: "Glasskube Package Guide"
    url: "https://glasskube.dev/products/package-manager/guides/how-to-add-a-package/"
  - label: "Repository"
    url: "https://github.com/pkhsu/glasskube-package-test/tree/main/apps/sample-web-app" 
